"""initial schema

Revision ID: 8bfaed8d6544
Revises: 
Create Date: 2026-04-19 21:48:50.854358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bfaed8d6544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('news_score', sa.Float(), nullable=True),
    sa.Column('indicator_score', sa.Float(), nullable=True),
    sa.Column('correlation_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('indicators_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_entry', sa.Float(), nullable=True),
    sa.Column('suggested_sl', sa.Float(), nullable=True),
    sa.Column('suggested_tp', sa.Float(), nullable=True),
    sa.Column('suggested_lots', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('analysis_summary_th', sa.Text(), nullable=True),
    sa.Column('errors_found', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('actual_outcome', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_pair_time', 'analyses', ['pair', sa.text('created_at DESC')], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('pair', sa.String(length=10), nullable=True),
    sa.Column('title_original', sa.Text(), nullable=False),
    sa.Column('title_th', sa.Text(), nullable=True),
    sa.Column('summary_original', sa.Text(), nullable=True),
    sa.Column('summary_th', sa.Text(), nullable=True),
    sa.Column('impact_level', sa.String(length=10), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('event_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_impact', 'news_items', ['impact_level', sa.text('scraped_at DESC')], unique=False)
    op.create_index('idx_news_pair_time', 'news_items', ['pair', sa.text('scraped_at DESC')], unique=False)
    op.create_table('system_diagnostics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.BigInteger(), nullable=True),
    sa.Column('diagnostic_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.BigInteger(), nullable=True),
    sa.Column('pair', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('account_balance', sa.Float(), nullable=False),
    sa.Column('risk_percent', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('tp_price', sa.Float(), nullable=True),
    sa.Column('sl_pips', sa.Float(), nullable=True),
    sa.Column('tp_pips', sa.Float(), nullable=True),
    sa.Column('target_pips', sa.Float(), nullable=True),
    sa.Column('target_hours', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('actual_pips', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('risk_reward_actual', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('system_confidence', sa.Float(), nullable=True),
    sa.Column('system_direction', sa.String(length=10), nullable=True),
    sa.Column('system_regime', sa.String(length=20), nullable=True),
    sa.Column('system_correct', sa.Boolean(), nullable=True),
    sa.Column('opened_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_opened', 'trades', ['opened_at'], unique=False)
    op.create_index('idx_trades_pair_status', 'trades', ['pair', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_pair_status', table_name='trades')
    op.drop_index('idx_trades_opened', table_name='trades')
    op.drop_table('trades')
    op.drop_table('system_diagnostics')
    op.drop_index('idx_news_pair_time', table_name='news_items')
    op.drop_index('idx_news_impact', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('idx_analysis_pair_time', table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
